name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]  # Add more browsers if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests with Mochawesome and Screenshots
        run: |
          npx cypress run --browser ${{ matrix.browser }} \
            --reporter mochawesome \
            --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true

      - name: Merge and Generate Mochawesome HTML Report (with screenshots)
        run: |
          npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/merged.json
          npx marge cypress/reports/mochawesome/merged.json \
            --reportDir cypress/reports/html \
            --reportFilename index.html \
            --inlineAssets true \
            --charts true

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: |
            cypress/reports/html/
            cypress/screenshots/
