name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]  # You can add 'firefox', 'electron' if desired

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests with Mochawesome Reporter
        run: |
          npx cypress run --browser ${{ matrix.browser }} \
            --reporter mochawesome \
            --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true
      

            - name: Generate Mochawesome HTML report
            run: |
              npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/merged.json
              npx marge cypress/reports/mochawesome/merged.json \
                --reportDir cypress/reports/html \
                --reportFilename index.html
          
  

      
