name: Cypress E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: |
          npx cypress run --browser ${{ matrix.browser }}

      - name: Merge JSONs and Generate HTML Report
        run: |
          npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/merged.json
          npx marge cypress/reports/mochawesome/merged.json \
            --reportDir cypress/reports/html \
            --reportFilename index.html \
            --inline

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html/
